/* Do not edit: file generated by auxprogs/make_or_upd_vgversion_h.
   This file defines VGGIT, used to report GIT revision
   when using command line options:  -v --version
   The produced VGGIT format is
      hhhhhhhhhh-YYYYMMDDX
   where hhhhhhhhhh is the first 10 characters of the HEAD commit
         YYYYMMDD is the commit date
         Trailing X is present if there are any (non untracked) modified files.
*/
#define VGGIT "608cb11914-20190413"
